### ISSUE TITLE
check some legal stuff

### ISSUE THREAD

**Issue by jkleinlercher** [rockaut/dynatrace-config#13]
@rockaut we need to check if and how this project can be used in our companies and can be worked on in our working time. I will check that in our company. Maybe you should do that also on your side?

**Comment by rockaut** [comment]
Usage shouldn't be a problem legally. First we own licenses (well I don't
know about you guys ;-) second we don't alter code.

As on the working side. I haven't worked on it while daytime but as it's
contributing to our internal solution and I am officially advised to work
on Dynatrace API I am pretty confident it's no problem... But asking isn't
any wrong.

Or did you mean something other?

jkleinlercher <notifications@github.com> schrieb am Mo., 25. Nov. 2019,
09:26:

**Comment by jkleinlercher** [comment]
@rockaut  it is not about the dynatrace product but concerning this open source project. We should add the apache 2.0 licence so every company can use this tool. is this ok for you?

**Comment by rockaut** [comment]
Absolutely!

**Comment by jkleinlercher** [comment]
from my side everything is done now. we have the apache 2 license in place and so we are fine.
