### ISSUE TITLE
Dynatrace developer instance

### ISSUE THREAD

**Issue by jkleinlercher** [rockaut/dynatrace-config#16]
See if https://www.dynatrace.com/developer/ instance can help with developing and testing (automated tests in ci pipeline)

**Comment by rockaut** [comment]
You mean that we can get an instance for this project. Good idea. Currently I'm only trying it against an environment on our cluster. Althought that has the upside that we can later also try to integrate the cluster api.

Anyways good idea! The https://www.dynatrace.com/developer/faq/ also reads pretty good and as we booth are paying customers there shouldn't be a problem.

**Comment by rockaut** [comment]
Ok I filed a request for an instance. Will update later.

**Comment by rockaut** [comment]
@jkleinlercher got the instance. I may add you with your email.
